products/urls.py
from django.conf.urls.defaults import *

import views
import quote.views

urlpatterns = patterns("",
    url(r'^$', views.index, name="product_home"),
    (r'^(?P<product_id>\d+)$', views.display_product),
    (r'^(?P<prod_var_id>\d+)/quote$', quote.views.add_line_item),
)

urls.py
import os

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin

import account.views
import quote.views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', account.views.login, name="acct_login"),
    url(r'^signup$', account.views.signup, name="acct_signup"),
    url(r'^activate', account.views.activate, name="acct_activate"),
    url(r'^logout$', account.views.logout, name="acct_logout"),
    (r'^user/(?P<user_id>\d+)/item_count$', account.views.line_item_quantity),
    (r'^user/(?P<user_id>\d+)/add_details$', account.views.add_details),

    (r'^products$', include('products.urls')),
    (r'^products/', include('products.urls')),

    (r'^quotation/', include('quote.urls')),

    (r'^admin/(.*)', admin.site.root),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
			{'document_root': os.path.join(os.path.dirname(__file__), 'site_media')}),
	)

products/models.py
from django.db import models
from datetime import datetime

class CommonInfo(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    class Meta:
	abstract = True

class Division(CommonInfo):
    def __unicode__(self):
	return self.name

class Category(CommonInfo):
    division = models.ForeignKey(Division)

    def __unicode__(self):
	return self.name

    class Meta:
	verbose_name_plural = "categories"

class Product(CommonInfo):
    category = models.ForeignKey(Category)
    code = models.CharField(max_length=50, unique=True)
    small_image = models.ImageField(upload_to="products/small")
    large_image = models.ImageField(upload_to="products/large")
    product_page = models.CharField(max_length=255)

    def __unicode__(self):
	return self.name

class Accessory(models.Model):
    product = models.ForeignKey(Product)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    part_number = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to="site_media/products/accessories", blank=True)
    accessory_page = models.CharField(max_length=255, blank=True)
    cost = models.DecimalField(max_digits=20, decimal_places=2)

    def __unicode__(self):
	return "%s - %s" % (self.description, self.product)

    class Meta:
	verbose_name_plural = "accessories"

class ProductVariant(models.Model):
    """Holds all part numbers and description of product variants. Many-to-one relationship with Product"""
    product = models.ForeignKey(Product)
    part_number = models.CharField(max_length=50, unique=True)
    weight = models.DecimalField(max_digits=5, decimal_places=1, default="0.5")
    description = models.TextField()
    cost = models.DecimalField(max_digits=20, decimal_places=2)

    def __unicode__(self):
	return "%s - %s" % (self.product, self.part_number)

    class Meta:
	verbose_name = "Product Variant"

quote/forms.py
from django.shortcuts import get_object_or_404
from django import forms
from django.http import Http404
from django.contrib.auth.models import User

from products.models import ProductVariant
from quote.models import *

import datetime

class LineItemForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput())
    user = forms.IntegerField(widget=forms.HiddenInput())

    def clean(self):
	if self._errors:
	    return
	if self.cleaned_data["quantity"] < 1:
	    raise forms.ValidationError("Invalid Quantity")

	return self.cleaned_data

    def save(self, prod_var_id):
	quantity = self.cleaned_data["quantity"]
	user = get_object_or_404(User, pk=self.cleaned_data["user"])

	try:
	    quotation = get_object_or_404(Quotation, user=user, status=0)
	except Http404:
	    quotation = Quotation.objects.create(user=user, time_created=datetime.datetime.now(), \
		    quotation_no=generate_quote_no(), cost=0, pdf=None, status=False)

	product = get_object_or_404(ProductVariant, pk=prod_var_id)

	try:
	    """ If line item already exists """
	    line_item = get_object_or_404(LineItem, product=product, quotation=quotation)
	    line_item.quantity += quantity  # update quantity
	    line_item.cost = str(float(line_item.cost) + float(product.cost) * int(quantity))	# update cost
	    line_item.save()
	    
	except Http404:
	    """ If line item doesn't exist, just create a new one """
	    line_item = LineItem.objects.create(quotation=quotation, product=product, quantity=quantity, \
		    cost_per_unit=product.cost, cost=str(float(product.cost) * int(quantity)))

	quotation.cost = str(float(quotation.cost) + float(line_item.cost))
	quotation.save()

	return line_item

class UserDetailCheckForm(forms.Form):
    company = forms.CharField(widget=forms.HiddenInput())

def prefix_zero(number):
    if number < 10:
	return "0" + str(number)

def generate_quote_no():
    today = datetime.datetime.now()
    no_of_quotes_this_month = Quotation.objects.filter(time_created__month=today.month).count()

    quote_no = "AGS "
    quote_no += prefix_zero(today.month) + "-"
    quote_no += str(today.year)[2:4] + "-"
    quote_no += prefix_zero(no_of_quotes_this_month + 1)

    return quote_no

product/views.py
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template import RequestContext

def index(request, template="product/index.html"):
    
    return render_to_response(template, {
    }, context_instance=RequestContext(request))

products/views.py
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from eqsupply.products.models import *
from eqsupply.quote.forms import LineItemForm

from eqsupply import helpers as h

APP_MENU = Division.objects.all()

@login_required
def index(request, template="products/index.html", **kwargs):
    categories = Category.objects.all()
    
    return render_to_response(template, {
	"menu": APP_MENU,
	"categories": categories,
    }, context_instance=RequestContext(request))

@login_required
def display_product(request, product_id, form_class=LineItemForm, template="products/product.html", **kwargs):
    product = get_object_or_404(Product, pk=product_id)
    form = form_class()

    return render_to_response(template, {
	"menu": APP_MENU,
	"product": product,
	"form": form,
    }, context_instance=RequestContext(request))

templates/products/base.html
{% extends "inner_base_with_menu.html" %}

{% block custom_js %}
    <script type="text/javascript" src="/site_media/js/quote.js"></script>
{% endblock %}

{% block body_id %}<body id="products">{% endblock %}

templates/products/index.html
{% extends "products/base.html" %}

{% block module %}
    <h2>All Categories</h2>
    <div id="product_list" class="viewport">
    {% for c in categories %}
	<h5>{{ c.name }}</h5>
	<ul class="products">
	{% for p in c.product_set.all %}
	    <li><a href="products/{{ p.id }}"><span style="background-image: url('/site_media/{{ p.small_image }}')"></span>{{ p.name }}</a></li>
	{% endfor %}
	    <div class="clear"></div>
	</ul>
    {% endfor %}
    </div>
{% endblock %}

templates/products/product.html
{% extends "products/base.html" %}

{% block module %}
    <h2>{{ product.category }}</h2>
    <div id="product" class="viewport">
	<div id="image" class="grid_4 alpha omega">
	    <img src="/site_media/{{ product.large_image }}"/>
	</div>
	<div id="detail" class="grid_12">
	    <h5>{{ product.name }}</h5>
	    <p>{{ product.description }}</p>
	    <div class="actions">
		<a target="blank" href="{{ product.product_page }}">View Product Page</a>
	    </div>
	    {% if product.productvariant_set.all %}
		<h5>Variants</h5>
		<table>
		    <thead>
			<tr>
			    <th>Part Number</th>
			    <th>Description</th>
			    <th></th>
			</tr>
		    </thead>
		    <tbody>
		    {% for pv in product.productvariant_set.all %}
			<tr class="pv_detail">
			    <td>{{ pv.part_number }}</td>
			    <td>{{ pv.description }}</td>
			    <td id="cell{{ pv.pk }}" class="activity">
				<a class="quote_btn" href="javascript:showQuoteForm('{{ pv.pk }}')"> + Quote</a>
				<form id="quote_{{ pv.pk }}_form" class="quote_form" action="javascript:quote('{{ pv.pk }}')">
				    {{ form.as_p }}
				    <input type="submit" value="Add"/>
				</form>
			    </td>
			</tr>
		    {% endfor %}
		    </tbody>
		</table>
	    {% endif %}
	    {% if product.accessory_set.all %}
		<h5>Accessories</h5>
		<table>
		    <tr>
			<th>Part Number</th>
			<th>Description</th>
			<th></th>
		    </tr>
		{% for a in product.accessory_set.all %}
		    <tr>
			<td>{{ a.part_number }}</td>
			<td>{{ a.description }}</td>
			<td id="cell{{ a.pk }}" class="activity">
			    <a class="quote_btn" href="javascript:showQuoteForm('{{ a.pk }}')"> + Quote</a>
			    <form id="quote_{{ a.pk }}_form" class="quote_form" action="javascript:">
				{{ form.as_p }}
				<input type="submit" value="Add"/>
			    </form>
			</td>
		    </tr>
		{% endfor %}
		</table>
	    {% endif %}
	</div>
	<div class="clear"></div>
    </div>
{% endblock %}

{% block page_js %}
    <script>
	$(function()	{
	    $(".quote_form label").remove();
	    $(".quote_form #id_user").attr("value", "{{ user.id }}");

	    $(".pv_detail").hover(
		function()  {},
		function()  {
		    $(".quote_form").hide();
		    $(".quote_btn").show();
		}
	    );

	});
    </script>
{% endblock %}